baseURL = "https://sinkingstone.com"
title = "sinking stone"
summaryLength = 2000

languageCode = "en"
defaultContentLanguage = "en"
hasCJKLanguage = false # Set `true` for Chinese/Japanese/Korean.
defaultContentLanguageInSubdir = false

# needed to render raw HTML (e.g. <sub>, <sup>, <kbd>, <mark>)
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
