baseURL = "https://sinkingstone.com"
title = "sinking stone"
author = "Bernardo Salazar"

theme = "paper"

[params]
  color = 'linen'

[pagination]
  pagerSize = 50

enableEmoji = true
enableGitInfo = false
# summaryLength = 200

languageCode = "en"
defaultContentLanguage = "en"
hasCJKLanguage = false # Set `true` for Chinese/Japanese/Korean.
defaultContentLanguageInSubdir = false

# Uncomment for google analytics
# googleAnalytics = UA-123-45

# needed to  render raw HTML (e.g. <sub>, <sup>, <kbd>, <mark>)
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
#  [markup.highlight]
#    lineNos = true

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10
  # [[menu.main]]
  #   identifier = "contact"
  #   name = "Contact"
  #   url = "/contact/"
  #   weight = 10

[privacy]
  [privacy.vimeo]
    disabled = false
    simple = true
  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true
  [privacy.instagram]
    disabled = false
    simple = true
  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]
  [services.instagram]
    disableInlineCSS = true
  [services.twitter]
    disableInlineCSS = true

# markup =
#   # Do not modify markup.highlight
#   highlight =
#     codeFences = false
#     noClasses = false
#   tableOfContents =
#     startLevel = 2
#     endLevel = 6
#     ordered = false
#   goldmark =
#     renderer =
#       unsafe = true
#
# taxonomies =
#   category = categories
#   tag = tags
#   series = series
#   author = authors
#
# timeZone = Europe/Madrid
#
# build =
#   useResourceCacheWhen = always
