main:
  - name: journal
    url: /categories/journal/
    weight: 1
  - name: reviews
    url: /categories/reviews/
    weight: 2
  - name: all
    url: /posts/
    weight: 3
  - name: about
    url: '/about'
    weight: 4
